
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4

      - name: Get Jdk
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Package with maven
        run: mvn clean package

    #Part Two
#Step to build Docker image
      - name: Build Docker Image
        run: docker build -t product_pipe_image

#Step to log in to Docker Hub
      - name: Log in to Docker Hub
        run: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

# Step to push Docker image to Docker Hub
      - name: Push Docker Image
        run: 
          docker tag product_pipe_image ${{secrets.DOCKER_USERNAME}}/product_pipe_image:latest \
          && docker push ${{secrets.DOCKER_USERNAME}}/product_pipe_image:latest